apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: front-end
  name: frontend-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 30010
  selector:
    app: front-end
  type: NodePort
status:
  loadBalancer: {}
